# Generated by Django 5.0.1 on 2024-01-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='category_id',
            new_name='category',
        ),
    ]
